#This is the name of workflow
name: hello workflow

on:
  workflow_dispatch: # this allows us to trigger the workflow manually from github UI
# Job inside the workflow
jobs:

# name of the job inside the workflow
  greet:
  #this is github runner : every job needs a separate runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: say hello to user
        run: echo "Hello from GitHub Actions!"
    
  timestamp:      
    runs-on: ubuntu-latest    
    steps:
      - name: Print current date and time
        run: date
      - name: Print branch name
        run: echo ${{ github.ref_name }}
      - name: List files in repo
        run: ls -la
      - name: Print runner OS
        run: echo $RUNNER_OS
 
  # details:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: show version of docker and python.
  #       run: docker --version && python --version