name: Matrix Python Versions

on:
  push:
  pull_request:

jobs:
  python-matrix:
    # name: Python #{{ matrix.python-version }}
    # runs-on: ubuntu-latest

    name: Ubuntu | Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest


    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
        exclude:
          - python-version: "3.10"
            os: windows-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}


      - name: Intentionally fail on Python 3.11
        if: matrix['python-version'] == '3.11'
        run: |
          echo "Failing on purpose to demonstrate fail-fast=false"
          exit 1
          
      - name: Succeed otherwise
        if: matrix['python-version'] != '3.11'
        run: echo "This job succeeds."


    

