name: Run Shell Script With Cache

on:
  workflow_dispatch:

jobs:
  test-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        
      - name: Prepare cache folder
        run: mkdir -p ~/.cache/custom

      # 1. Cache apt packages and other downloads

      - name: Cache script downloads
        uses: actions/cache@v4
        with:
            path: ~/.cache/custom
            key: ${{ runner.os }}-${{ hashFiles('Scripts/run.sh') }}
            restore-keys: |
                ${{ runner.os }}-



      # 2. Make script executable
      - name: Ensure script is executable
        run: chmod +x Scripts/run.sh

      # 3. Run your shell script
      - name: Run script (non-zero exit -> fail job)
        run: ./Scripts/run.sh