
name: Secrets Demo

on: [push]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker registry (Docker Hub)
        env:
          DOCKER_USERNAME: ${{ vars.DOCKERHUB_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin




    # task2    
    #   - name: Call script using secret (example)
    #     env:
    #       API_TOKEN: {{ secrets.MY_SECRET_MESSAGE }}
    #     run: |
    #       # Example usage: pass as header or argument (DO NOT echo the value)
    #       curl -sS -H "Authorization: Bearer $API_TOKEN" https://google.com || true

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   # Step-level env: pass the secret as an environment variable
    #   - name: Use secret as env var (without printing it)
    #     env:
    #       MY_SECRET_MESSAGE: {{ secrets.MY_SECRET_MESSAGE }}
    #     run: |
    #         if [ -n "{{ secrets.MY_SECRET_MESSAGE }}" ]; then
    #           echo "The secret is set: true"
    #         else
    #           echo "The secret is set: false"
    #         fi


          
            
    # Task-1       
    #   - name: Print whether secret exists
    
    #     run: |
    #       if [ -n "{{ secrets.MY_SECRET_MESSAGE }}" ]; then
    #         echo "The secret is set: true"
    #       else
    #         echo "The secret is set: false"
    #       fi

    #   - name: Print the secret value  
    #     run: |
    #         echo "The secret value is: {{ secrets.MY_SECRET_MESSAGE }}"    
