name: Version Check Workflow

on:
    workflow_dispatch: # this allows us to trigger the workflow manually from github UI

jobs:
    tools:
        runs-on: ubuntu-latest
        steps:
            - name: Check Docker version
              run: docker --version

            - name: Check Python version
              run: python --version

            - name: Check Node.js version
              run: node --version
              
            - name: Check Git Version
              run: git --version
